- name: Recovery Compilation
  uses: CarbonatedBlack/Recovery-Compiler@production
  env:
    MANIFEST: "Recovery Manifest URL with -b branch" or "orangefox" for orangefox android v10
    DT_LINK: "Your Device Tree Link"
    VENDOR: "Your Device's Vendor name as in used inside DT. Example: xiaomi, samsung, asus, etc."
    CODENAME: "Your Device's Codename as in used inside DT. Example: nikel, phoenix, ginkgo, etc."
    KERNEL_LINK: "Kernel repo link with optional -b branch. If not filled it would be detected as prebuilt"
    TARGET: "Set as recoveryimage or bootimage if no recovery partition avaiable"
    FLAVOR: "eng or userdebug"
    EXTRA_CMD: "if you want to Execute any external Command Before Compilation Starts"
    TZ: "Asia/Kolkata" # Set Time-Zone According To Your Region
